[tool.poetry]
name = "splunk-contentctl"
version = "0.1.0"
description = "Tools for initializing, building, testing, releasing, and installing Security Content Apps to Splunk"
authors = ["Splunk Threat Research Team <research@splunk.com>"]

[tool.poetry.dependencies]
python = "^3.9"
attackcti = "^0.3.7"
docker = "^6.0.0"
GitPython = "^3.1.27"
Jinja2 = "^3.1.2"
jsonschema = "^4.14.0"
mock = "^4.0.3"
pycvesearch = "^1.2"
pydantic = "^1.9.2"
pytest = "^7.1.2"
questionary = "^1.10.0"
requests = "^2.28.1"
six = "^1.16.0"
splunk-sdk = "^1.7.1"
wrapt-timeout-decorator = "^1.3.12"
xmltodict = "^0.13.0"
beautifulsoup4 = "^4.11.1"
pysigma = "^0.8.1"
pysigma-backend-splunk = "^0.3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
